name: Deploy to GAE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug Secrets
        run: |
          echo "GCP_PROJECT: ${{ secrets.GCP_PROJECT }}"
          # Print the length of the credentials to ensure they are being accessed correctly
          echo "Length of GCP_CREDENTIALS: $(echo "${{ secrets.GCP_CREDENTIALS }}" | wc -c)"

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: configs/appengine/app.yaml
          version: v1
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"